# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox' do |vb|
    vb.check_guest_additions = false
    vb.name = 'ubuntu2310-password'
    vb.memory = '768'
    vb.cpus = '1'
  end

  config.vm.box = 'eldipa-seclab/ubuntu2310-password'
  config.vm.hostname = "ubuntu2310-password"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "introsec"
  config.vm.graceful_halt_timeout = 5
  config.vm.box_check_update = false
  config.vm.boot_timeout = 420

  # Disable NFS sharing (==> default: Mounting NFS shared folders...)
  config.vm.synced_folder ".", "/vagrant", type: "nfs", disabled: true

end
